### ISSUE TITLE
Erro ao atualizar de 3.1.5 para 3.1.6

### ISSUE THREAD

**Issue by DanielSvoboda** [CostelaCNX/CNX-Updater#3]
Ao tentar atualizar pelo switch da versão 3.1.5 para 3.1.6, apresente esse erro: not_an_archive
Também não da pra sair dessa tela. Só se bloquear ele, e tentar ir para a tela inicial sem abrir o 'jogo' e de qualquer forma acaba crashando ou travando tudo a ponto de ter q reiniciar.
![image](https://github.com/user-attachments/assets/3f564bd1-dfa1-40b6-b46f-a2ef13993f59)

**Comment by victorfabiani** [comment]
Mesma coisa aqui.

**Comment by haroldo-rg** [comment]
Mesmo erro aqui

**Comment by DanielsSan28** [comment]
Aqui msm coisa!

**Comment by CostelaCNX** [comment]
Lembram quando eu fixei a mensagem ao abri o CNX UPDATER, pra quem atualizou o PACOTE ANTES DOS DIA 21/10/24 ( Data que minhas contas foram hackeadas e derrubadas ) baixar novamente o pacote? Então ESTAVA ESCRTITO LÁ que quem não o fizesse não iria funcionar o AUTO UPDATE, pois aquele build não pertencia a esse REPO do git... Baixem manualmente a 3.1.6 direto ou usem a 3.1.5 desse REPO, que o auto update vai funcionar!
