### ISSUE TITLE
Erro ao atualizar versão 3.1.5 para 3.1.6

### ISSUE THREAD

**Issue by DanielsSan28** [CostelaCNX/CNX-Updater#4]
![IMG_20241018_104304](https://github.com/user-attachments/assets/f2f1d62b-89c3-4561-97d5-0386d8ced36d)
Não consigo atualizar de jeito nenhum, eu entro vejo que precisa atualizar coloco pra atualizar, porém dá esse erro e trava o Nintendo tendo que reiniciar ele, tela não funciona nem botões.

**Comment by haroldo-rg** [comment]
Problema já reportado nessa issue:
https://github.com/CostelaCNX/CNX-Updater/issues/3

**Comment by CostelaCNX** [comment]
duplicidade
