### ISSUE TITLE
Congelando e reiniciando 

### ISSUE THREAD

**Issue by VBaldochi** [CostelaCNX/CNX-Updater#6]
Ao iniciar atualização, primeiro informou que o arquivo baixado não estava no formato ZIP e congelou o console, após reiniciar o console e tentar novamente ele apresentou erro e reiniciou.

**Comment by VBaldochi** [comment]
https://github.com/user-attachments/assets/1d990e0f-c6aa-4e13-85e4-e08d9ed9b886

**Comment by arthuruepa** [comment]
Estou com o mesmo problema

**Comment by CostelaCNX** [comment]
Duplicidade de issue #3
