### ISSUE TITLE
Erro ao atualizar pelo Switch

### ISSUE THREAD

**Issue by YgorzinPKM** [CostelaCNX/CNX-Updater#7]
Opa, tudo bem? Estou tentando atualizar o CNX pelo meu Switch mas não vai, e além de dar erro trava o meu console. O erro fala algo referente a um arquivo .zip mas não lembro exatamente.

**Comment by YgorzinPKM** [comment]
Acabei de tentar novamente, aparece  seguinte mensagem: "O arquivo baixado não é um arquivo .zip. Isto provavelmente aconteceu devido a um link quebrado. Se o problema persistir depois de 30 minutos, por favor, abra um "issue" no Github."

**Comment by CostelaCNX** [comment]
Mesmo erro #3
