### ISSUE TITLE
Erro ao atualizar 

### ISSUE THREAD

**Issue by filipecoimbra222** [CostelaCNX/CNX-Updater#8]
Boa noite! Ao tentar atualizar para o pacote CNX 19.0.0-2, o processo de atualização segue normalmente, mas após finalizar, um erro do Hekate aparece e após sair dele. um processo do payload RCM 3.2 inicia e recebo uma mensagem de erro que diz:

"Arquivo de exclusão não encontrado!

Existem problemas com alguns prerrequisitos ou com o seu sd e o processo não pode continuar."

Após isso, fica neste loop entre o erro do Hekate e o erro do payload do Updater. Tendo como única opção desligar o console a força segurando o botão power. Além disso, o updater regride da versão 3.1.6 para a 3.1.5 por algum motivo.  Segue abaixo os erros que acontecem:

![Hecate](https://github.com/user-attachments/assets/edef0086-55e3-45a7-acdf-3aa7111c6714)
![WhatsApp Image 2024-10-20 at 21 36 16](https://github.com/user-attachments/assets/e0137b67-0e1a-4f8a-a1ee-256d646ffa1e)

**Comment by CostelaCNX** [comment]
Consegue compartilhar comigo a versão do pacote que vc está usando no momento e o arquivo log_atualizacao.txt que está no seu sd por favor

**Comment by filipecoimbra222** [comment]
> Consegue compartilhar comigo a versão do pacote que vc está usando no momento e o arquivo log_atualizacao.txt que está no seu sd por favor

O ar pacote atual está 19.0.0-2 (Mesmo com o erro, reiniciando forçado o console, a atualização aparentemente completa normalmente. Agora o aquivo log_atualizacao fica em branco... Posso mandar, mas fica como aviso que ele está totalmente vazio.

**Comment by filipecoimbra222** [comment]
> Consegue compartilhar comigo a versão do pacote que vc está usando no momento e o arquivo log_atualizacao.txt que está no seu sd por favor

@CostelaCNX retificando, os logs do sistema estavam desligado por padrão (???) e consegui gerar o log. Segue abaixo.

[log_atualizacao.txt](https://github.com/user-attachments/files/17452791/log_atualizacao.txt)

**Comment by CostelaCNX** [comment]
@filipecoimbra222 obrigado, mas digo antes de vc atualizar o pacote, ele estava em qual? Você lembra?

**Comment by filipecoimbra222** [comment]
> @filipecoimbra222 obrigado, mas digo antes de vc atualizar o pacote, ele estava em qual? Você lembra?
> 
> Ah e a questão de "regredir" para 3.1.5, é pq no pacote o updater ainda é o 3.1.5

A versão que estava anteriormente era a CNX 18.1.0-4. Atualizei direto para a 19.0.0-2. Foi quando o erro aconteceu.

**Comment by filipecoimbra222** [comment]
> Já foi identificado a falha, indica problema no cartão sd e ou incompatibilidade do bdk, vai ser feito um update no programa, para que ele use sempre o bdk do pacote novo e não do velho pra evitar essas fadigas. Obrigado pelo report, a ajuda de vocês é essencial sempre!

Valeu Costela. Você é essencial para a comunidade de CFW do Switch. Obrigado pelo trabalho!
